<?php

return [
    'providers' => [
        // Electricity Providers
        'iesco' => [
            'slug' => 'iesco-bill-online',
            'type' => 'electricity',
            'key' => 'iesco',
            'name' => 'IESCO',
            'full_name' => 'Islamabad Electric Supply Company',
            'utility_type_label' => 'Electricity',
            'coverage_area' => ['Islamabad', 'Rawalpindi', 'Attock', 'Jhelum', 'Chakwal'],
            'hub_url' => '/electricity-bill-online',
            'hub_name' => 'Electricity Bill Online',
            'image_path' => 'storage/img/iesco.jpg',
            'related_providers' => ['lesco', 'mepco', 'fesco', 'ke'],
        ],
        'lesco' => [
            'slug' => 'lesco-bill-online',
            'type' => 'electricity',
            'key' => 'lesco',
            'name' => 'LESCO',
            'full_name' => 'Lahore Electric Supply Company',
            'utility_type_label' => 'Electricity',
            'coverage_area' => ['Lahore', 'Kasur', 'Sheikhupura', 'Nankana Sahib'],
            'hub_url' => '/electricity-bill-online',
            'hub_name' => 'Electricity Bill Online',
            'image_path' => 'storage/img/lesco.png',
            'related_providers' => ['iesco', 'mepco', 'fesco', 'ke'],
        ],
        'mepco' => [
            'slug' => 'mepco-bill-online',
            'type' => 'electricity',
            'key' => 'mepco',
            'name' => 'MEPCO',
            'full_name' => 'Multan Electric Power Company',
            'utility_type_label' => 'Electricity',
            'coverage_area' => ['Multan', 'Khanewal', 'Vehari', 'Lodhran'],
            'hub_url' => '/electricity-bill-online',
            'hub_name' => 'Electricity Bill Online',
            'image_path' => 'storage/img/mepco.png',
            'related_providers' => ['iesco', 'lesco', 'fesco', 'pesco'],
        ],
        'fesco' => [
            'slug' => 'fesco-bill-online',
            'type' => 'electricity',
            'key' => 'fesco',
            'name' => 'FESCO',
            'full_name' => 'Faisalabad Electric Supply Company',
            'utility_type_label' => 'Electricity',
            'coverage_area' => ['Faisalabad', 'Jhang', 'Toba Tek Singh', 'Chiniot'],
            'hub_url' => '/electricity-bill-online',
            'hub_name' => 'Electricity Bill Online',
            'image_path' => 'storage/img/fesco.png',
            'related_providers' => ['lesco', 'mepco', 'gepco', 'iesco'],
        ],
        'pesco' => [
            'slug' => 'pesco-bill-online',
            'type' => 'electricity',
            'key' => 'pesco',
            'name' => 'PESCO',
            'full_name' => 'Peshawar Electric Supply Company',
            'utility_type_label' => 'Electricity',
            'coverage_area' => ['Peshawar', 'Mardan', 'Charsadda', 'Nowshera'],
            'hub_url' => '/electricity-bill-online',
            'hub_name' => 'Electricity Bill Online',
            'image_path' => 'storage/img/pesco.png',
            'related_providers' => ['iesco', 'lesco', 'mepco', 'fesco'],
        ],
        'gepco' => [
            'slug' => 'gepco-bill-online',
            'type' => 'electricity',
            'key' => 'gepco',
            'name' => 'GEPCO',
            'full_name' => 'Gujranwala Electric Power Company',
            'utility_type_label' => 'Electricity',
            'coverage_area' => ['Gujranwala', 'Sialkot', 'Gujrat', 'Narowal'],
            'hub_url' => '/electricity-bill-online',
            'hub_name' => 'Electricity Bill Online',
            'image_path' => 'storage/img/gepco.jpg',
            'related_providers' => ['lesco', 'fesco', 'iesco', 'mepco'],
        ],
        'hesco' => [
            'slug' => 'hesco-bill-online',
            'type' => 'electricity',
            'key' => 'hesco',
            'name' => 'HESCO',
            'full_name' => 'Hyderabad Electric Supply Company',
            'utility_type_label' => 'Electricity',
            'coverage_area' => ['Hyderabad', 'Mirpur Khas', 'Sanghar', 'Tharparkar'],
            'hub_url' => '/electricity-bill-online',
            'hub_name' => 'Electricity Bill Online',
            'image_path' => 'storage/img/hesco.jpg',
            'related_providers' => ['sepco', 'qesco', 'iesco', 'lesco'],
        ],
        'sepco' => [
            'slug' => 'sepco-bill-online',
            'type' => 'electricity',
            'key' => 'sepco',
            'name' => 'SEPCO',
            'full_name' => 'Sukkur Electric Power Company',
            'utility_type_label' => 'Electricity',
            'coverage_area' => ['Sukkur', 'Larkana', 'Shikarpur', 'Ghotki'],
            'hub_url' => '/electricity-bill-online',
            'hub_name' => 'Electricity Bill Online',
            'image_path' => 'storage/img/sepco.png',
            'related_providers' => ['hesco', 'qesco', 'iesco', 'lesco'],
        ],
        'qesco' => [
            'slug' => 'qesco-bill-online',
            'type' => 'electricity',
            'key' => 'qesco',
            'name' => 'QESCO',
            'full_name' => 'Quetta Electric Supply Company',
            'utility_type_label' => 'Electricity',
            'coverage_area' => ['Quetta', 'Sibi', 'Zhob', 'Loralai'],
            'hub_url' => '/electricity-bill-online',
            'hub_name' => 'Electricity Bill Online',
            'image_path' => 'storage/img/qesco.png',
            'related_providers' => ['hesco', 'sepco', 'iesco', 'lesco'],
        ],
        'tesco' => [
            'slug' => 'tesco-bill-online',
            'type' => 'electricity',
            'key' => 'tesco',
            'name' => 'TESCO',
            'full_name' => 'Tribal Electric Supply Company',
            'utility_type_label' => 'Electricity',
            'coverage_area' => ['Tribal Areas', 'Khyber', 'Bajaur', 'Mohmand'],
            'hub_url' => '/electricity-bill-online',
            'hub_name' => 'Electricity Bill Online',
            'image_path' => 'storage/img/tesco.png',
            'related_providers' => ['pesco', 'iesco', 'lesco', 'mepco'],
        ],
        'ke' => [
            'slug' => 'k-electric-bill-online',
            'type' => 'electricity',
            'key' => 'ke',
            'name' => 'K-Electric',
            'full_name' => 'Karachi Electric',
            'utility_type_label' => 'Electricity',
            'coverage_area' => ['Karachi', 'Dhabeji', 'Gharo', 'Bela'],
            'hub_url' => '/electricity-bill-online',
            'hub_name' => 'Electricity Bill Online',
            'image_path' => 'storage/img/kelectric.jpg',
            'related_providers' => ['iesco', 'lesco', 'mepco', 'fesco'],
        ],

        // Gas Providers
        'sngpl' => [
            'slug' => 'sngpl-bill-online',
            'type' => 'gas',
            'key' => 'sngpl',
            'name' => 'SNGPL',
            'full_name' => 'Sui Northern Gas Pipelines Ltd.',
            'utility_type_label' => 'Gas',
            'coverage_area' => ['Punjab', 'KPK', 'Islamabad'],
            'hub_url' => '/gas-bill-online',
            'hub_name' => 'Gas Bill Online',
            'image_path' => 'storage/img/sngpl.png',
            'related_providers' => ['ssgc'],
        ],
        'ssgc' => [
            'slug' => 'ssgc-bill-online',
            'type' => 'gas',
            'key' => 'ssgc',
            'name' => 'SSGC',
            'full_name' => 'Sui Southern Gas Company',
            'utility_type_label' => 'Gas',
            'coverage_area' => ['Sindh', 'Balochistan', 'Karachi'],
            'hub_url' => '/gas-bill-online',
            'hub_name' => 'Gas Bill Online',
            'image_path' => 'storage/img/ssgc.png',
            'related_providers' => ['sngpl'],
        ],

        // Internet Providers
        'ptcl' => [
            'slug' => 'ptcl-bill-online',
            'type' => 'internet',
            'key' => 'ptcl',
            'name' => 'PTCL',
            'full_name' => 'Pakistan Telecommunication Company Limited',
            'utility_type_label' => 'Internet',
            'coverage_area' => ['Nationwide'],
            'hub_url' => '/internet-bill-online',
            'hub_name' => 'Internet Bill Online',
            'image_path' => 'storage/img/ptcl.jpg',
            'related_providers' => ['nayatel', 'stormfiber'],
        ],
        'nayatel' => [
            'slug' => 'nayatel-bill-online',
            'type' => 'internet',
            'key' => 'nayatel',
            'name' => 'Nayatel',
            'full_name' => 'Nayatel Fiber Internet',
            'utility_type_label' => 'Internet',
            'coverage_area' => ['Islamabad', 'Rawalpindi', 'Lahore'],
            'hub_url' => '/internet-bill-online',
            'hub_name' => 'Internet Bill Online',
            'image_path' => 'storage/img/nayatel.jpg',
            'related_providers' => ['ptcl', 'stormfiber'],
        ],
        'stormfiber' => [
            'slug' => 'stormfiber-bill-online',
            'type' => 'internet',
            'key' => 'stormfiber',
            'name' => 'StormFiber',
            'full_name' => 'StormFiber Broadband',
            'utility_type_label' => 'Internet',
            'coverage_area' => ['Karachi', 'Lahore', 'Islamabad'],
            'hub_url' => '/internet-bill-online',
            'hub_name' => 'Internet Bill Online',
            'image_path' => 'storage/img/stormfiber.png',
            'related_providers' => ['ptcl', 'nayatel'],
        ],
    ],
];
